Repository SOPT-all/35-SOPKATHON-WEB-web2, pull requests merged in 2024-11, with the labels that each got.

#8 [ setting ] svgr 초기 세팅
  package.json
  public/vite.svg
  vite.config.js
  yarn.lock
Labels: 🧩 Setting

#12 [design] 모임 개설 페이지 퍼블리싱
  src/Layout.jsx
  src/pages/groups/NewGroup.jsx
  src/styles/theme.js
Labels: 🎨 Design

#20 [ feat ] 유효성 검사 로직 구현
  package.json
  src/pages/groups/Hint.jsx
  src/pages/groups/NewGroup.jsx
Labels: 🔧 Feature, 🎨 Design

#23 [ feat ] 모임 개설 페이지 모달 구현
  .gitignore
  src/apis/axiosInstance.jsx
  src/components/NewGroup/Modal.jsx
  src/pages/groups/NewGroup.jsx
Labels: 🔧 Feature, 🎨 Design

#30 [ feat ] 참여 요청 api 수정
  src/apis/searchApi.js
  src/components/Search/Modal.jsx
Labels: ⚙️ Fix
